-- MySQL Script generated by MySQL Workbench
-- Thu Jan 31 22:30:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema starforce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starforce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starforce` DEFAULT CHARACTER SET utf8 ;
USE `starforce` ;

-- -----------------------------------------------------
-- Table `starforce`.`jednostki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`jednostki` (
  `ID` INT NOT NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`wystawcy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`wystawcy` (
  `ID` INT NOT NULL,
  `nazwa` VARCHAR(200) NOT NULL,
  `kontakt` VARCHAR(300) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`typ_sprzetu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`typ_sprzetu` (
  `ID` INT NOT NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`wystawy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`wystawy` (
  `ID` INT NOT NULL,
  `nazwa` VARCHAR(200) NOT NULL,
  `termin` DATE NULL,
  `ostatnia_wizyta` DATE NULL,
  `problemy` INT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`magazyny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`magazyny` (
  `ID` INT NOT NULL,
  `nazwa` VARCHAR(200) NOT NULL,
  `kontakt` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`zaplecze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`zaplecze` (
  `wystawy_ID` INT NOT NULL,
  `magazyny_ID` INT NOT NULL,
  `ilosc_stolow` INT NULL,
  `ilosc_gablot` INT NULL,
  `ilosc_barier_stalowych` INT NULL,
  `ilosc_barier_slupkowych` INT NULL,
  `ilosc_krzesel` INT NULL,
  `szerokosc_stolu` DECIMAL(10,2) NULL,
  `dlugosc_stolu` DECIMAL(10,2) NULL,
  `szerokosc_gabloty` DECIMAL(10,2) NULL,
  `dlugosc_gabloty` DECIMAL(10,2) NULL,
  `dlugosc_bariery_stalowej` DECIMAL(10,2) NULL,
  `dlugosc_bariery_slupkowej` DECIMAL(10,2) NULL,
  `pobrane_stoly` INT NULL,
  `pobrane_gabloty` INT NULL DEFAULT 0,
  `pobrane_barierki_slupkowe` INT NULL DEFAULT 0,
  `pobrane_barierki_stalowe` INT NULL DEFAULT 0,
  `pobrane_krzesla` INT NULL DEFAULT 0,
  PRIMARY KEY (`wystawy_ID`, `magazyny_ID`),
  INDEX `fk_magazyny_wystawy1_idx` (`wystawy_ID` ASC) VISIBLE,
  INDEX `fk_zaplecze_magazyny1_idx` (`magazyny_ID` ASC) VISIBLE,
  CONSTRAINT `fk_magazyny_wystawy1`
    FOREIGN KEY (`wystawy_ID`)
    REFERENCES `starforce`.`wystawy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaplecze_magazyny1`
    FOREIGN KEY (`magazyny_ID`)
    REFERENCES `starforce`.`magazyny` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`zapotrzebowanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`zapotrzebowanie` (
  `wystawcy_ID` INT NOT NULL,
  `wystawy_ID` INT NOT NULL,
  `typ_sprzetu_ID` INT NOT NULL,
  `ilosc_podana` DECIMAL(10,2) NOT NULL,
  `ilosc_przeliczona` INT NULL,
  `jednostki_ID` INT NOT NULL,
  `zaplecze_magazyny_ID` INT NULL,
  PRIMARY KEY (`wystawcy_ID`, `wystawy_ID`, `typ_sprzetu_ID`),
  INDEX `fk_zapotrzebowanie_wystawcy_idx` (`wystawcy_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_jednostki1_idx` (`jednostki_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_typ_sprzetu1_idx` (`typ_sprzetu_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_wystawy1_idx` (`wystawy_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_zaplecze1_idx` (`zaplecze_magazyny_ID` ASC) VISIBLE,
  CONSTRAINT `fk_zapotrzebowanie_wystawcy`
    FOREIGN KEY (`wystawcy_ID`)
    REFERENCES `starforce`.`wystawcy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_jednostki1`
    FOREIGN KEY (`jednostki_ID`)
    REFERENCES `starforce`.`jednostki` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_typ_sprzetu1`
    FOREIGN KEY (`typ_sprzetu_ID`)
    REFERENCES `starforce`.`typ_sprzetu` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_wystawy1`
    FOREIGN KEY (`wystawy_ID`)
    REFERENCES `starforce`.`wystawy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_zaplecze1`
    FOREIGN KEY (`zaplecze_magazyny_ID`)
    REFERENCES `starforce`.`zaplecze` (`magazyny_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`zaplecze_archiwum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`zaplecze_archiwum` (
  `wystawy_ID` INT NOT NULL,
  `magazyny_ID` INT NOT NULL,
  `edycja` DATE NOT NULL,
  `ilosc_stolow` INT NULL,
  `ilosc_gablot` INT NULL,
  `ilosc_barier_stalowych` INT NULL,
  `ilosc_barier_slupkowych` INT NULL,
  `ilosc_krzesel` INT NULL,
  `szerokosc_stolu` DECIMAL(10,2) NULL,
  `dlugosc_stolu` DECIMAL(10,2) NULL,
  `szerokosc_gabloty` DECIMAL(10,2) NULL,
  `dlugosc_gabloty` DECIMAL(10,2) NULL,
  `dlugosc_bariery_stalowej` DECIMAL(10,2) NULL,
  `dlugosc_bariery_slupkowej` DECIMAL(10,2) NULL,
  PRIMARY KEY (`edycja`, `magazyny_ID`, `wystawy_ID`),
  INDEX `fk_magazyny_wystawy1_idx` (`wystawy_ID` ASC) VISIBLE,
  INDEX `fk_zaplecze_archiwum_magazyny1_idx` (`magazyny_ID` ASC) VISIBLE,
  CONSTRAINT `fk_magazyny_wystawy10`
    FOREIGN KEY (`wystawy_ID`)
    REFERENCES `starforce`.`wystawy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaplecze_archiwum_magazyny1`
    FOREIGN KEY (`magazyny_ID`)
    REFERENCES `starforce`.`magazyny` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starforce`.`zapotrzebowanie_archiwum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starforce`.`zapotrzebowanie_archiwum` (
  `wystawcy_ID` INT NOT NULL,
  `wystawy_ID` INT NOT NULL,
  `typ_sprzetu_ID` INT NOT NULL,
  `edycja` DATE NOT NULL,
  `ilosc_podana` DECIMAL(10,2) NOT NULL,
  `ilosc_przeliczona` INT NULL,
  `jednostki_ID` INT NOT NULL,
  `zaplecze_archiwum_magazyny_ID` INT NULL,
  PRIMARY KEY (`wystawcy_ID`, `wystawy_ID`, `typ_sprzetu_ID`, `edycja`),
  INDEX `fk_zapotrzebowanie_wystawcy_idx` (`wystawcy_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_jednostki1_idx` (`jednostki_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_typ_sprzetu1_idx` (`typ_sprzetu_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_archiwum_wystawy1_idx` (`wystawy_ID` ASC) VISIBLE,
  INDEX `fk_zapotrzebowanie_archiwum_zaplecze_archiwum1_idx` (`zaplecze_archiwum_magazyny_ID` ASC) VISIBLE,
  CONSTRAINT `fk_zapotrzebowanie_wystawcy0`
    FOREIGN KEY (`wystawcy_ID`)
    REFERENCES `starforce`.`wystawcy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_jednostki10`
    FOREIGN KEY (`jednostki_ID`)
    REFERENCES `starforce`.`jednostki` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_typ_sprzetu10`
    FOREIGN KEY (`typ_sprzetu_ID`)
    REFERENCES `starforce`.`typ_sprzetu` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_archiwum_wystawy1`
    FOREIGN KEY (`wystawy_ID`)
    REFERENCES `starforce`.`wystawy` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapotrzebowanie_archiwum_zaplecze_archiwum1`
    FOREIGN KEY (`zaplecze_archiwum_magazyny_ID`)
    REFERENCES `starforce`.`zaplecze_archiwum` (`magazyny_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `starforce`;

DELIMITER $$
USE `starforce`$$
CREATE DEFINER = CURRENT_USER TRIGGER `starforce`.`wystawy_BEFORE_UPDATE` BEFORE UPDATE ON `wystawy` FOR EACH ROW
BEGIN
	IF NEW.termin<NEW.ostatnia_wizyta THEN 
    BEGIN
		INSERT INTO zaplecze_archiwum (magazyny_ID, wystawy_ID, ilosc_stolow, ilosc_gablot, ilosc_barier_stalowych, ilosc_barier_slupkowych, ilosc_krzesel, szerokosc_stolu, dlugosc_stolu, szerokosc_gabloty, dlugosc_gabloty, dlugosc_bariery_stalowej, dlugosc_bariery_slupkowej, edycja)
									SELECT zaplecze.magazyny_ID, zaplecze.wystawy_ID, zaplecze.ilosc_stolow, zaplecze.ilosc_gablot, zaplecze.ilosc_barier_stalowych, zaplecze.ilosc_barier_slupkowych, zaplecze.ilosc_krzesel, zaplecze.szerokosc_stolu, zaplecze.dlugosc_stolu, zaplecze.szerokosc_gabloty, zaplecze.dlugosc_gabloty, zaplecze.dlugosc_bariery_stalowej, zaplecze.dlugosc_bariery_slupkowej, NEW.termin
                                    FROM zaplecze WHERE zaplecze.wystawy_ID=new.ID;
		INSERT INTO zapotrzebowanie_archiwum (wystawy_ID, wystawcy_ID, typ_sprzetu_ID, ilosc_podana, ilosc_przeliczona, jednostki_ID, zaplecze_archiwum_magazyny_ID, edycja)
									  SELECT zapotrzebowanie.wystawy_ID, zapotrzebowanie.wystawcy_ID, zapotrzebowanie.typ_sprzetu_ID, zapotrzebowanie.ilosc_podana, zapotrzebowanie.ilosc_przeliczona, zapotrzebowanie.jednostki_ID, zapotrzebowanie.zaplecze_magazyny_ID, NEW.termin
                                      FROM zapotrzebowanie WHERE zapotrzebowanie.wystawy_ID=new.ID;
		
        
	
	END;
	END IF;
END;$$

USE `starforce`$$
CREATE DEFINER = CURRENT_USER TRIGGER `starforce`.`zaplecze_AFTER_UPDATE` AFTER UPDATE ON `zaplecze` FOR EACH ROW
BEGIN
UPDATE wystawy SET problemy=(SELECT count(*) FROM zaplecze WHERE pobrane_stoly>ilosc_stolow AND wystawy_ID=NEW.wystawy_ID)+
                            (SELECT count(*) FROM zaplecze WHERE pobrane_gabloty>ilosc_gablot AND wystawy_ID=NEW.wystawy_ID)+
							(SELECT count(*) FROM zaplecze WHERE pobrane_barierki_slupkowe>ilosc_barier_slupkowych AND wystawy_ID=NEW.wystawy_ID)+
                            (SELECT count(*) FROM zaplecze WHERE pobrane_barierki_stalowe>ilosc_barier_stalowych AND wystawy_ID=NEW.wystawy_ID)+
                            (SELECT count(*) FROM zaplecze WHERE pobrane_krzesla>ilosc_krzesel AND wystawy_ID=NEW.wystawy_ID)
			    WHERE NEW.wystawy_ID=wystawy.ID;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
